![image.png](attachment:60d88a7a-0d38-437f-ad30-d4c03674fdb3.png)

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('weatherAUS.csv', encoding='utf-8', usecols=['Date', 'Location', 'MinTemp', 'MaxTemp'])

In [3]:
#Drop records where target MinTemp=NaN or MaxTemp=NaN
df = df.dropna(subset=['MinTemp', 'MaxTemp'])

In [4]:
# Convert dates to year-months
df['Year-Month']= (pd.to_datetime(df['Date'], yearfirst=True)).dt.strftime('%Y-%m')

In [5]:
# Derive median daily temperature (mid point between Daily Max and Daily Min)
df['MedTemp']=df[['MinTemp', 'MaxTemp']].median(axis=1)

In [6]:
df

             Date          Location  MinTemp  MaxTemp Year-Month  MedTemp
0      2008-12-01            Albury     13.4     22.9    2008-12    18.15
1      2008-12-02            Albury      7.4     25.1    2008-12    16.25
2      2008-12-03            Albury     12.9     25.7    2008-12    19.30
3      2008-12-04            Albury      9.2     28.0    2008-12    18.60
4      2008-12-05            Albury     17.5     32.3    2008-12    24.90
...           ...               ...      ...      ...        ...      ...
65293  2012-02-07  MelbourneAirport     10.9     21.2    2012-02    16.05
65294  2012-02-08  MelbourneAirport      8.9     21.7    2012-02    15.30
65295  2012-02-09  MelbourneAirport      9.2     26.0    2012-02    17.60
65296  2012-02-10  MelbourneAirport     15.3     25.8    2012-02    20.55
65297  2012-02-11  MelbourneAirport     14.5     20.9    2012-02    17.70

[64463 rows x 6 columns]

## Aggregate to monthly averages

In [7]:
# Create a copy of an original dataframe
df2=df[['Location', 'Year-Month', 'MedTemp']].copy()

In [8]:
# Calculate monthly average temperature for each location
df2 = df2.groupby(['Location', 'Year-Month'], as_index=False)['MedTemp'].mean()

In [9]:
# Transpose dataframe
# Pivot to wide format
df2_pivot = df2.pivot(index='Location', columns='Year-Month', values='MedTemp')

In [10]:
df2_pivot

Year-Month,2007-11,2007-12,2008-01,2008-02,2008-03,2008-04,2008-05,2008-06,2008-07,2008-08,...,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06
Location,,,,,,,,,,,,,,,,,,,,,
Albury,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.213333,13.617742,18.170000,22.677419,25.298387,23.239286,23.067742,15.516667,11.417742,7.972000
BadgerysCreek,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.766667,17.037097,21.485000,25.065385,26.430645,25.107143,22.050000,17.205000,14.372581,12.766000
Ballarat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.426667,10.600000,13.428333,17.345161,19.833871,17.835714,19.145161,13.046667,9.427419,7.102000
Bendigo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.011667,12.595161,16.818333,21.022581,23.114516,21.066071,22.262903,15.251667,11.029630,8.054000
Canberra,18.403333,19.216129,22.237097,18.636207,18.427419,12.341667,9.885484,9.475000,5.803226,6.585484,...,10.295000,11.838710,16.700000,21.098387,23.853226,21.483929,19.343548,12.708333,9.014516,6.444000
Cobar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.121667,17.475806,22.846667,27.277419,30.686207,29.042857,26.117742,19.016667,14.582258,11.576000
CoffsHarbour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.513793,18.382258,21.339655,23.661290,25.209677,24.735714,22.838710,19.211667,17.398387,16.089583
MelbourneAirport,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Moree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.043333,18.154839,23.233333,28.216129,30.775806,29.792857,25.245161,19.293333,16.612903,13.166000
MountGinini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.748333,4.767742,10.358333,13.627419,16.467742,14.573214,12.429032,7.151667,4.009677,3.336000
Newcastle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.526923,18.301786,21.668333,24.688000,26.279630,26.359091,23.309091,19.215385,15.795455,14.640909
NorahHead,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.098333,18.709677,21.350000,23.085484,24.870968,23.875000,22.793548,19.440000,17.104839,15.166000
NorfolkIsland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.730000,17.996774,19.425000,20.695161,22.262903,23.555357,22.432258,21.581667,19.640000,17.696000
Penrith,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.121667,18.448387,22.660000,25.485484,27.229032,26.098214,22.867742,18.325000,15.400000,13.554000
Richmond,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.438333,17.800000,22.153333,25.033871,27.080645,25.839286,22.819355,17.788333,14.380645,12.798000
Sale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.321667,13.587097,15.621667,19.129032,20.398387,18.905357,19.866129,14.891667,11.527419,9.196000
Sydney,NaN,NaN,NaN,21.627586,21.216129,17.711667,15.967742,15.258333,12.751613,12.733871,...,17.215000,19.108065,21.730000,24.085484,25.591935,24.757143,22.788710,19.203333,16.866129,14.458000
SydneyAirport,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.228333,19.008065,21.733333,24.301613,25.670968,24.764286,22.813333,19.098333,16.764516,14.328000
Tuggeranong,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.311667,12.256452,17.071667,21.074194,23.617742,21.637500,19.532258,12.918333,9.179032,6.722000
WaggaWagga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.848333,13.580645,18.511667,23.538710,26.351613,24.117857,23.082258,16.281667,11.701613,7.844000
Williamtown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.310000,18.116129,21.156667,24.496774,25.870968,25.642857,22.743548,18.436667,15.667742,14.228000
Wollongong,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.216667,17.701613,19.908621,22.358065,23.691935,22.742857,21.662903,18.528333,16.469355,14.538000

In [11]:
# Remove locations with excessive missing values (NaN)
df2_pivot = df2_pivot.drop(
    ['Dartmoor', 'Katherine', 'Melbourne', 'Nhil', 'Uluru'],
    axis=0, errors='ignore'
)

In [12]:
# Remove months with lots of missing data (NaN)
df2_pivot=df2_pivot.drop(['2007-11', '2007-12', '2008-01', '2008-02', '2008-03', '2008-04', '2008-05', '2008-06', '2008-07', '2008-08', '2008-09', '2008-10', '2008-11', '2008-12', '2017-01', '2017-02', '2017-03', '2017-04', '2017-05', '2017-06'], axis=1)

In [13]:
df2_pivot

Year-Month,2009-01,2009-02,2009-03,2009-04,2009-05,2009-06,2009-07,2009-08,2009-09,2009-10,...,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12
Location,,,,,,,,,,,,,,,,,,,,,
Albury,25.485484,25.439286,20.535484,15.410000,11.716129,9.206667,8.201613,9.932258,11.951786,14.595161,...,23.290323,17.580000,13.069355,9.500000,9.517742,9.625806,12.213333,13.617742,18.170000,22.677419
BadgerysCreek,24.467742,22.948214,20.877419,17.305000,14.312903,11.769643,10.727419,12.520968,15.558333,16.646429,...,22.938710,19.743333,15.164516,12.613333,12.053226,11.940323,14.766667,17.037097,21.485000,25.065385
Ballarat,19.498387,19.605357,16.440323,12.175000,10.222581,7.768333,7.108065,8.366129,9.555000,11.288710,...,18.667742,14.500000,11.006452,7.238333,7.224194,7.943548,9.426667,10.600000,13.428333,17.345161
Bendigo,22.995161,22.932143,18.941935,14.511667,12.095161,8.640000,7.837097,9.635484,10.696667,13.859677,...,22.119355,16.440000,12.324194,8.596667,9.111290,9.154839,11.011667,12.595161,16.818333,21.022581
Canberra,22.512903,21.523214,19.219355,14.030000,10.343548,8.023333,6.827419,8.267742,10.676667,12.614516,...,20.122581,16.068333,11.074194,8.013333,7.456452,7.700000,10.295000,11.838710,16.700000,21.098387
Cobar,29.264516,26.864286,24.611290,18.898333,14.756452,12.123333,10.833871,14.095161,16.546667,19.229032,...,25.532258,21.925000,15.651613,11.528333,10.969355,11.638710,13.121667,17.475806,22.846667,27.277419
CoffsHarbour,23.301613,23.274074,22.158065,19.828333,16.774194,14.343333,13.509677,16.058065,17.341667,19.064516,...,23.261290,21.310000,17.751613,15.416667,14.079032,14.908065,17.513793,18.382258,21.339655,23.661290
MelbourneAirport,21.116129,21.067857,18.587097,15.078333,12.335484,10.220000,9.854839,11.600000,12.831667,13.706452,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Moree,27.238710,25.946429,23.774194,19.895000,15.461290,12.940000,11.370968,15.030645,16.683333,20.220968,...,26.458065,22.911667,17.017742,12.898333,12.277419,12.743548,15.043333,18.154839,23.233333,28.216129
MountGinini,15.966129,14.298214,12.140323,6.480000,4.129032,1.116071,-0.541667,1.459259,4.635714,5.387500,...,13.495161,9.950000,4.848387,1.451667,0.753226,1.072581,3.748333,4.767742,10.358333,13.627419
Newcastle,24.430645,23.792857,22.219355,18.813889,16.335000,13.882143,12.600000,14.890323,16.965789,18.542593,...,22.542105,20.538000,17.569643,14.257500,14.275000,14.261111,16.526923,18.301786,21.668333,24.688000
NorahHead,23.090000,22.085714,22.298387,19.343333,17.112903,15.213793,13.748387,15.951613,17.789655,18.159091,...,22.750000,21.046667,18.198387,15.308333,14.516129,15.085484,17.098333,18.709677,21.350000,23.085484
NorfolkIsland,21.545161,23.407143,22.179032,21.006667,17.711290,17.200000,16.035484,16.608065,17.193333,17.283333,...,23.103226,21.881667,20.106452,18.100000,17.370968,16.175806,17.730000,17.996774,19.425000,20.695161
Penrith,25.791935,24.030357,22.090323,18.240000,15.470968,12.641667,11.819355,13.676667,17.090000,18.187097,...,24.129032,20.841667,16.329032,13.143333,12.637097,13.003226,16.121667,18.448387,22.660000,25.485484
Richmond,24.277419,23.642857,21.401613,17.741667,14.390323,12.056667,10.991935,12.724194,16.230000,17.146774,...,23.106667,19.900000,15.308065,12.843333,12.122581,12.133871,15.438333,17.800000,22.153333,25.033871
Sale,19.685484,19.258929,17.806452,14.006667,11.103226,9.080000,9.262903,10.909677,12.233333,13.161290,...,19.266129,15.665000,12.904839,9.576667,9.929032,9.879032,12.321667,13.587097,15.621667,19.129032
Sydney,23.729032,22.708929,22.156452,19.245000,16.601613,14.065000,13.751613,15.617742,18.265000,17.746774,...,23.214516,20.805000,18.067742,14.951667,14.245161,14.458065,17.215000,19.108065,21.730000,24.085484
SydneyAirport,24.146774,22.867857,22.474194,19.113333,16.403226,14.198333,13.383871,15.708065,18.211667,17.979032,...,23.314516,20.805000,18.069355,15.071667,14.425806,14.508065,17.228333,19.008065,21.733333,24.301613
Tuggeranong,22.701613,21.887500,19.135484,14.090000,10.329032,7.900000,6.838710,8.145161,10.721667,12.816129,...,20.070968,15.828333,10.679032,7.990000,7.390323,7.714516,10.311667,12.256452,17.071667,21.074194
WaggaWagga,26.177419,25.891071,21.500000,16.218333,12.880645,9.943333,8.435484,9.806452,12.265000,15.398387,...,23.490323,18.420000,12.954839,9.880000,9.500000,9.548387,11.848333,13.580645,18.511667,23.538710
Williamtown,23.777419,23.385714,21.206452,18.585000,15.770968,13.156667,11.982258,14.172581,16.816667,17.172581,...,22.882258,19.918333,16.762903,13.920000,13.029032,13.070968,16.310000,18.116129,21.156667,24.496774
Wollongong,22.146774,21.162500,21.162903,18.206667,16.541379,14.633333,13.641935,15.593548,17.135000,16.890323,...,21.464516,20.120000,17.785484,14.828333,14.320968,14.561290,16.216667,17.701613,19.908621,22.358065

In [14]:
# Remove months with insufficient data
months_to_drop = [
    '2007-11','2007-12',
    '2008-01','2008-02','2008-03','2008-04','2008-05','2008-06',
    '2008-07','2008-08','2008-09','2008-10','2008-11','2008-12',
    '2017-01','2017-02','2017-03','2017-04','2017-05','2017-06'
]
df2_pivot = df2_pivot.drop(months_to_drop, axis=1, errors='ignore')

In [15]:
# Add missing months 2011-04, 2011-04, 2011-04 and impute data
df2_pivot['2011-04']=(df2_pivot['2011-03']+df2_pivot['2011-05'])/2
df2_pivot['2012-12']=(df2_pivot['2012-11']+df2_pivot['2013-01'])/2
df2_pivot['2013-02']=(df2_pivot['2013-01']+df2_pivot['2013-03'])/2

In [16]:
# Sort columns so Year-Months are in the correct order
df2_pivot=df2_pivot.reindex(sorted(df2_pivot.columns), axis=1)

In [17]:
import plotly.graph_objects as go

In [18]:
# Plot average monthly temperature derived from daily medians for each location
fig = go.Figure()
for location in df2_pivot.index:
    fig.add_trace(go.Scatter(x=df2_pivot.loc[location, :].index,
                             y=df2_pivot.loc[location, :].values,
                             mode='lines', name=location,
                             opacity=0.8, line=dict(width=1)
                            ))

In [19]:
# Change chart background color
fig.update_layout(dict(plot_bgcolor = 'white'), showlegend=True)

# Update axes lines
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='lightgrey',
                 zeroline=True, zerolinewidth=1, zerolinecolor='lightgrey',
                 showline=True, linewidth=1, linecolor='black',
                 title='Date'
                )

fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='lightgrey',
                 zeroline=True, zerolinewidth=1, zerolinecolor='lightgrey',
                 showline=True, linewidth=1, linecolor='black',
                 title='Degrees Celsius'
                )

# Set figure title
fig.update_layout(title=dict(text="Average Monthly Temperatures", font=dict(color='black')))

fig.show()

In [20]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler # for feature scaling

In [21]:
def shaping(datain, timestep, scaler):

    # Convert input dataframe to array and flatten
    arr = datain.to_numpy().flatten()

    # Scale
    arr=scaler.fit_transform(arr.reshape(-1, 1)).flatten()

    X_list, y_list = [], []
    for i in range(len(datain.columns) - 2 * timestep + 1):
        X_list.append(arr[i:i+timestep])
        y_list.append(arr[i+timestep:i+2*timestep])

    # Reshape input and target arrays
    X_out = np.array(X_list).reshape(-1, timestep, 1)
    y_out = np.array(y_list).reshape(-1, timestep, 1)
    return X_out, y_out

In [22]:
##### Step 1 - Specify parameters
timestep=18
location='Canberra'
scaler = MinMaxScaler(feature_range=(-1, 1))

In [23]:
##### Step 2 - Prepare data

# Split data into train and test dataframes
df_train=df2_pivot.iloc[:, :-2*timestep].copy()
df_test=df2_pivot.iloc[:, -2*timestep:].copy()

In [24]:
# Select one location
dfloc_train = df_train[df_train.index==location].copy()
dfloc_test = df_test[df_test.index==location].copy()

In [25]:
# Use previously defined shaping function to reshape the data for LSTM
X_train, y_train = shaping(datain=dfloc_train, timestep=timestep, scaler=scaler)
X_test, y_test = shaping(datain=dfloc_test, timestep=timestep, scaler=scaler)

In [28]:
from tensorflow import keras # for building Neural Networks
from keras.models import Sequential # for creating a linear stack of layers for our Neural Network
from keras import Input # for instantiating a keras tensor
from keras.layers import Bidirectional, GRU, RepeatVector, Dense, TimeDistributed # for creating layers inside the Neural Network

In [29]:
##### Step 3 - Specify the structure of a Neural Network
model = Sequential(name="GRU-Model")
# Input Layer - need to speicfy the shape of inputs
model.add(Input(shape=(X_train.shape[1],X_train.shape[2]), name='Input-Layer'))
# Encoder Layer
model.add(Bidirectional(GRU(units=32, activation='tanh', recurrent_activation='sigmoid', stateful=False), name='Hidden-GRU-Encoder-Layer'))
# Repeat Vector
model.add(RepeatVector(y_train.shape[1], name='Repeat-Vector-Layer'))
# Decoder Layer
model.add(Bidirectional(GRU(units=32, activation='tanh', recurrent_activation='sigmoid', stateful=False, return_sequences=True), name='Hidden-GRU-Decoder-Layer'))
# Output Layer, Linear(x) = x
model.add(TimeDistributed(Dense(units=1, activation='linear'), name='Output-Layer'))

In [30]:
##### Step 4 - Compile the model
model.compile(
    optimizer='adam', loss='mean_squared_error',
    metrics=['mean_squared_error', 'mean_absolute_error']
)

In [31]:
history = model.fit(X_train, y_train,
    batch_size=1, epochs=100,
    validation_split=0.2, shuffle=True, verbose=0
)

In [32]:
##### Step 6 - Use model to make predictions
# Predict results on training data
pred_train = model.predict(X_train)
# Predict esults on test data
pred_test = model.predict(X_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 944ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 914ms/step

In [33]:
##### Step 7 - Print Performance Summary
print("")
print('-------------------- Model Summary --------------------')
model.summary() # print model summary
print("")
print('-------------------- Weights and Biases --------------------')
print("Too many parameters to print but you can use the code provided if needed")
print("")
for layer in model.layers:
    print(layer.name)
    for item in layer.get_weights():
        print("  ", item)
print("")

-------------------- Model Summary --------------------

Model: "GRU-Model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Hidden-GRU-Encoder-Layer        │ (None, 64)             │         6,720 │
│ (Bidirectional)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Repeat-Vector-Layer             │ (None, 18, 64)         │             0 │
│ (RepeatVector)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden-GRU-Decoder-Layer        │ (None, 18, 64)         │        18,816 │
│ (Bidirectional)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Output-Layer (TimeDistributed)  │ (None, 18, 1)          │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 76,805 (300.02 KB)

 Trainable params: 25,601 (100.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 51,204 (200.02 KB)

-------------------- Weights and Biases --------------------
Too many parameters to print but you can use the code provided if needed

Hidden-GRU-Encoder-Layer
   [[-0.24027364  0.11046555  0.06112798 -0.0827658  -0.13918868 -0.08174156
   0.18484952 -0.03102376 -0.18047419 -0.04316073  0.11295387 -0.07330168
   0.03719921 -0.11705028 -0.08119508  0.03977317 -0.32613474 -0.31684962
   0.09436706 -0.20479406  0.23346534  0.23352844 -0.06929137  0.14916937
  -0.18725365  0.00844097  0.25902498  0.18743293 -0.01605956 -0.01267636
   0.04065394  0.26060966  0.137394    0.07851608  0.10033967  0.0053982
  -0.24705821  0.03921718  0.01801443 -0.00301058  0.11410897  0.03172617
   0.21704842  0.2423369   0.21851736  0.20501149 -0.1743063   0.18199973
   0.11492573 -0.04526303  0.07213899  0.2014318  -0.09283075 -0.01278038
   0.07534823  0.10524254 -0.04081941 -0.01424351 -0.21180587 -0.13604905
   0.10752355  0.00470971  0.03701663 -0.12397398 -0.20252508  0.12889214
   0.2284076  -0.05918078 -0.15641269  0.26531023  0.03842363  0.25462568
   0.05990371 -0.04181457  0.03628485 -0.04303842  0.03527943 -0.07676231
  -0.05123751 -0.09147789 -0.06514975  0.19846192  0.193107   -0.14932369
  -0.22675133  0.03772811 -0.02317457 -0.2686354   0.076765   -0.06087398
  -0.25309384 -0.1035978  -0.19401488 -0.13659272  0.05242582  0.20449091]]
   [[ 0.12188298  0.01694327 -0.07147934 ...  0.02767066 -0.17317778
   0.04146102]
 [-0.06985457  0.04791453  0.02202052 ...  0.05858788 -0.19181044
  -0.15758887]
 [-0.16360311  0.08873801 -0.10475214 ... -0.06585409 -0.1722688
   0.12603118]
 ...
 [-0.03573453  0.02053611  0.05128718 ... -0.09104549  0.01988865
   0.03657887]
 [-0.03260418 -0.05064142  0.00588485 ... -0.18354897 -0.04923847
   0.15134406]
 [-0.2381963  -0.23575933 -0.06560162 ...  0.04750654 -0.0112514
  -0.05464985]]
   [[ 1.06696840e-02  1.08404681e-02 -9.42954421e-03 -2.15285216e-02
  -1.36199053e-02 -3.10015380e-02 -1.04379863e-01 -5.67990020e-02
   7.55899586e-03  8.14835206e-02  8.70730504e-02 -4.14646529e-02
  -3.25404555e-02  2.77677476e-02 -1.23987300e-02 -6.25384226e-02
  -1.35248238e-02 -3.85274179e-02  7.02443020e-03  3.37552130e-02
   1.33496942e-05  1.90692069e-03 -5.72497137e-02 -2.10301839e-02
  -3.37626226e-02 -2.93045072e-04 -2.66797021e-02 -6.01364346e-03
   1.55843375e-02  6.63029170e-03  6.25934312e-03  3.03001963e-02
  -2.85549574e-02  7.34997541e-02  8.10389817e-02  2.49422602e-02
   4.04677317e-02 -4.95303869e-02  8.57516825e-02  8.66836309e-02
  -7.03099137e-03  1.25169940e-02 -1.43640200e-02  5.15369140e-02
   4.00575995e-02  5.77378261e-04  1.23295255e-01  1.38709098e-01
   4.86530662e-02 -6.91069942e-03  3.07433829e-02 -1.14246726e-03
  -3.65282968e-02 -2.61988137e-02  4.06362824e-02  9.80511159e-02
   8.78909975e-02  9.32767093e-02  5.75123169e-02  3.65610328e-03
  -4.50706817e-02  3.87224667e-02 -3.14972661e-02  1.14092296e-02
   4.15264163e-03  2.25796569e-02  1.33796344e-02  8.25504307e-03
   5.14986599e-03  1.54234460e-02  1.10501414e-02  8.01215041e-03
  -1.26580643e-02  8.24904442e-03 -1.13629354e-02  1.08104320e-02
   9.65031888e-03 -6.07674476e-03 -4.61856835e-02 -1.96441673e-02
  -3.74191743e-03 -4.88854805e-03 -2.08508465e-02 -1.47774285e-02
  -3.29181668e-04  9.76017769e-03 -2.66462006e-03  9.94060392e-05
   1.21940523e-02 -3.17014791e-02 -2.14146432e-02 -9.65422660e-04
  -5.69568621e-03 -3.44619714e-03 -4.26412153e-04 -1.16292555e-02]
 [ 1.06696840e-02  1.08404681e-02 -9.42954421e-03 -2.15285216e-02
  -1.36199053e-02 -3.10015380e-02 -1.04379863e-01 -5.67990020e-02
   7.55899586e-03  8.14835206e-02  8.70730504e-02 -4.14646529e-02
  -3.25404555e-02  2.77677476e-02 -1.23987300e-02 -6.25384226e-02
  -1.35248238e-02 -3.85274179e-02  7.02443020e-03  3.37552130e-02
   1.33496942e-05  1.90692069e-03 -5.72497137e-02 -2.10301839e-02
  -3.37626226e-02 -2.93045072e-04 -2.66797021e-02 -6.01364346e-03
   1.55843375e-02  6.63029170e-03  6.25934312e-03  3.03001963e-02
  -2.85549574e-02  7.34997541e-02  8.10389817e-02  2.49422602e-02
   4.04677317e-02 -4.95303869e-02  8.57516825e-02  8.66836309e-02
  -7.03099137e-03  1.25169940e-02 -1.43640200e-02  5.15369140e-02
   4.00575995e-02  5.77378261e-04  1.23295255e-01  1.38709098e-01
   4.86530662e-02 -6.91069942e-03  3.07433829e-02 -1.14246726e-03
  -3.65282968e-02 -2.61988137e-02  4.06362824e-02  9.80511159e-02
   8.78909975e-02  9.32767093e-02  5.75123169e-02  3.65610328e-03
  -4.50706817e-02  3.87224667e-02 -3.14972661e-02  1.14092296e-02
   5.23670809e-03  2.30167639e-02  1.44004412e-02  8.57896544e-03
   3.89404828e-03  1.50991939e-02  1.05596390e-02  8.70139711e-03
  -1.49185108e-02  8.38314276e-03 -1.25567866e-02  1.17298728e-02
   1.10351881e-02 -5.43845305e-03 -4.48668934e-02 -2.13471688e-02
  -1.11727789e-03 -8.26091226e-03 -2.00286973e-02 -1.56737436e-02
   9.48829547e-05  9.35688708e-03 -2.04298412e-03 -3.49086185e-04
   1.21957706e-02 -3.20943370e-02 -2.09938306e-02 -4.77126974e-04
  -4.54362109e-03 -2.95149814e-03 -2.91239424e-03 -1.06387846e-02]]
   [[-0.11124352  0.20319311  0.20580544 -0.05012411 -0.12211773 -0.05936369
  -0.1442035   0.17229937  0.07950332 -0.13709567  0.12955074  0.05616552
   0.15868397 -0.11898852  0.27771124 -0.16335925 -0.16722327 -0.03531642
   0.04489214 -0.029175    0.06716221  0.15016393 -0.09731386  0.14292683
   0.16663656  0.2825274  -0.12813099  0.16699986  0.11093199  0.02220355
  -0.03262564  0.08964101  0.2185621  -0.09232058 -0.07988415 -0.17215069
  -0.3232579  -0.02555312  0.09540277  0.27244082  0.1571655   0.24983278
   0.11485458 -0.0093061   0.09756414 -0.04394107  0.15094303 -0.11742891
   0.03201738 -0.27363887  0.269011   -0.02542529  0.20668255 -0.03802856
   0.36441103 -0.18546559  0.11956324 -0.29715353 -0.05518373 -0.0977723
  -0.07572539  0.07646531 -0.04214758  0.22588296 -0.07251822 -0.24011327
   0.15766236 -0.12046082  0.11127759 -0.0539655  -0.19647583  0.00464277
  -0.04959664 -0.15398045  0.23197572  0.17300889  0.01278702 -0.01327605
   0.02681659 -0.29366332 -0.22182073 -0.0775049  -0.15177657 -0.2042172
  -0.20289692 -0.13661538 -0.03542345 -0.09967923 -0.24637419  0.19817972
  -0.21667653 -0.2909394   0.11026061  0.08114884  0.04508472 -0.06571666]]
   [[-0.10432193  0.04360465 -0.11599132 ... -0.09639255 -0.09113687
  -0.07049412]
 [-0.16062203  0.00390908 -0.21265107 ...  0.04479111 -0.14408545
   0.07046825]
 [ 0.009902    0.05572023  0.08785854 ...  0.04194671 -0.03461302
  -0.03592672]
 ...
 [-0.05356197  0.15844184  0.07633156 ... -0.00239979  0.08474473
   0.2401271 ]
 [ 0.05627619  0.15878615  0.10010044 ...  0.05323419  0.10424399
   0.08581322]
 [-0.1025769  -0.06909246  0.02132433 ... -0.09923884  0.10690253
   0.10465929]]
   [[ 1.50608728e-02 -5.11502754e-03  7.44988322e-02  9.62710194e-03
   7.14206398e-02 -1.39750224e-02 -2.75539830e-02 -6.25843462e-03
   3.49226668e-02 -5.60392104e-02 -3.00089754e-02 -1.55672024e-03
  -7.76951090e-02  2.53537390e-03  2.20471919e-02 -5.23953326e-03
   2.25772616e-02 -6.07531816e-02 -2.33242679e-02  4.11830284e-02
  -1.27060451e-02  5.82104661e-02  8.09527785e-02  4.08535041e-02
  -8.99328366e-02 -5.64033240e-02  4.48310450e-02 -2.71737371e-02
   7.08753020e-02 -1.39664831e-02 -1.71664190e-02 -3.35119925e-02
   4.06681113e-02  1.52502861e-02  1.08544499e-01  6.15390912e-02
   1.88664749e-01 -3.13906819e-02  4.14384492e-02  3.73786781e-03
   6.05170429e-02  5.77435642e-02  1.44214649e-02 -5.95476665e-03
   7.16431290e-02  1.39564335e-01 -1.87599529e-02  3.30615602e-02
   2.72556338e-02  8.92871395e-02 -1.02230674e-02  2.88897175e-02
   2.61347983e-02  2.32213810e-02  6.81985915e-02  1.89049020e-02
  -1.69303477e-01  8.68845284e-02  4.04784121e-02  2.27138679e-02
   1.33951887e-01 -6.40526935e-02  3.14035602e-02  8.95341635e-02
  -6.48968574e-03 -9.02230106e-03  2.59228218e-02  9.34415380e-04
   6.07122201e-03  8.03107955e-03 -9.43426043e-03 -2.07758974e-02
  -8.72152485e-03  1.30455531e-02 -2.64804158e-02 -7.50283385e-03
   2.48938682e-03 -1.07123991e-02 -1.23511755e-03 -6.29256945e-03
   2.58356798e-04  1.77887473e-02 -1.29936365e-02 -1.37111284e-02
  -9.85256024e-03 -1.07838027e-02  1.82562899e-02  2.31783334e-02
   8.81716982e-03 -1.31361168e-02 -4.87928931e-03  8.19603971e-04
   1.19601460e-02  9.83550400e-03  1.63750127e-02  3.64370085e-02]
 [ 1.50608728e-02 -5.11502754e-03  7.44988322e-02  9.62710194e-03
   7.14206398e-02 -1.39750224e-02 -2.75539830e-02 -6.25843462e-03
   3.49226668e-02 -5.60392104e-02 -3.00089754e-02 -1.55672024e-03
  -7.76951090e-02  2.53537390e-03  2.20471919e-02 -5.23953326e-03
   2.25772616e-02 -6.07531816e-02 -2.33242679e-02  4.11830284e-02
  -1.27060451e-02  5.82104661e-02  8.09527785e-02  4.08535041e-02
  -8.99328366e-02 -5.64033240e-02  4.48310450e-02 -2.71737371e-02
   7.08753020e-02 -1.39664831e-02 -1.71664190e-02 -3.35119925e-02
   4.06681113e-02  1.52502861e-02  1.08544499e-01  6.15390912e-02
   1.88664749e-01 -3.13906819e-02  4.14384492e-02  3.73786781e-03
   6.05170429e-02  5.77435642e-02  1.44214649e-02 -5.95476665e-03
   7.16431290e-02  1.39564335e-01 -1.87599529e-02  3.30615602e-02
   2.72556338e-02  8.92871395e-02 -1.02230674e-02  2.88897175e-02
   2.61347983e-02  2.32213810e-02  6.81985915e-02  1.89049020e-02
  -1.69303477e-01  8.68845284e-02  4.04784121e-02  2.27138679e-02
   1.33951887e-01 -6.40526935e-02  3.14035602e-02  8.95341635e-02
  -7.25558819e-03 -8.08431674e-03  2.48210505e-02  2.05521402e-03
   1.69193227e-05  7.67809711e-03 -8.93836748e-03 -1.95697006e-02
  -7.56467925e-03  9.40842927e-03 -2.51483824e-02 -7.25253765e-03
   4.14380385e-03 -8.65244400e-03 -2.52200058e-03 -6.87080901e-03
   1.01312168e-03  1.63546298e-02 -1.42018870e-02 -1.38096465e-02
  -1.31303994e-02 -1.11302761e-02  1.74074378e-02  1.87608004e-02
   3.86520359e-03 -1.03536118e-02 -3.20051145e-03  1.78505492e-03
   8.56572762e-03  8.94031301e-03  1.73454080e-02  3.58901247e-02]]
Repeat-Vector-Layer
Hidden-GRU-Decoder-Layer
   [[ 0.17137122  0.22985758 -0.18915057 ...  0.18712412  0.02003726
   0.20695545]
 [-0.16577424  0.01464947  0.02130972 ...  0.16875964 -0.22518621
  -0.08019385]
 [-0.00690399 -0.15271132 -0.09090386 ... -0.18728971  0.07437635
   0.15062307]
 ...
 [-0.08441023  0.12283616  0.08595309 ...  0.14889674 -0.12766
   0.18789801]
 [ 0.00652886  0.01354164 -0.18726863 ...  0.12930183  0.14016153
  -0.1944723 ]
 [-0.15034114 -0.24053524 -0.14957789 ... -0.05779978  0.18791236
  -0.13569354]]
   [[-0.18705052 -0.25981373  0.06927221 ...  0.04351921 -0.07015811
   0.28060564]
 [ 0.11859027 -0.09725062 -0.03377896 ...  0.09941445  0.13426517
   0.11651849]
 [-0.03156156  0.03183359  0.15817979 ...  0.06620896 -0.12406816
   0.04546986]
 ...
 [ 0.0005722   0.02092397 -0.10635678 ...  0.1837708   0.15193942
   0.07447054]
 [ 0.05171013  0.08136062 -0.02087234 ... -0.14328139  0.13388659
  -0.06625381]
 [ 0.10846397  0.15722986 -0.01812905 ...  0.08849376  0.1822473
  -0.09391025]]
   [[ 4.5132518e-02 -2.4273008e-02  1.9902078e-02  5.9368405e-02
   3.0867897e-02  1.8878855e-02 -3.3543162e-02  4.9705807e-02
  -6.9644928e-02 -6.3394785e-02 -8.9246273e-02 -4.6463888e-02
  -4.1849028e-02 -5.5349652e-02  1.2674037e-02 -1.7557837e-02
  -1.4891520e-02 -6.3702755e-02 -6.4269200e-02  9.7864205e-03
   2.4665290e-02 -1.6126746e-02  2.4041560e-02 -5.9633899e-02
  -2.6616180e-02 -3.0393042e-02  4.5375239e-02 -1.2577372e-02
   9.3190998e-02 -3.5703909e-02  9.0370312e-02 -3.4779113e-02
   1.3009547e-01  1.4527279e-01 -6.8328403e-02  6.1714694e-02
   1.0496302e-01  7.4521162e-02  7.9241514e-02  1.2149208e-01
   9.2848070e-02  1.6383871e-01  8.3695039e-02  1.1862928e-01
   8.4960550e-02  1.1424400e-01  4.4447754e-02 -1.4369994e-02
   1.7353597e-01  9.0383328e-02  7.3721111e-02  1.5649934e-01
   1.2394750e-01  5.7008471e-02  2.8602382e-02  1.5170257e-01
   2.2256730e-01  8.2103282e-02  3.8832251e-02  1.1789430e-01
   7.2601624e-03  1.2687095e-01  3.5189770e-02  2.0796658e-01
   3.8890732e-03  1.7346056e-02  4.7565922e-03  2.0390435e-03
  -9.8284008e-03 -2.9327560e-03 -5.7865921e-03 -5.0612804e-03
  -8.9187996e-04  7.9245074e-03 -1.3720159e-03 -2.7508728e-02
   5.7790950e-03 -1.6503673e-02 -1.6229317e-02 -2.4593826e-02
  -6.3606545e-02 -2.5434632e-02  3.1609831e-03 -7.9758437e-03
  -1.9438792e-02  1.1735198e-02  9.3466062e-03  2.4843048e-02
   3.8649045e-02 -1.4615964e-02  1.2357212e-02 -5.0847512e-04
  -2.5317178e-05  2.7140582e-03  4.4473191e-03  8.7450361e-03]
 [ 4.5132518e-02 -2.4273008e-02  1.9902078e-02  5.9368405e-02
   3.0867897e-02  1.8878855e-02 -3.3543162e-02  4.9705807e-02
  -6.9644928e-02 -6.3394785e-02 -8.9246273e-02 -4.6463888e-02
  -4.1849028e-02 -5.5349652e-02  1.2674037e-02 -1.7557837e-02
  -1.4891520e-02 -6.3702755e-02 -6.4269200e-02  9.7864205e-03
   2.4665290e-02 -1.6126746e-02  2.4041560e-02 -5.9633899e-02
  -2.6616180e-02 -3.0393042e-02  4.5375239e-02 -1.2577372e-02
   9.3190998e-02 -3.5703909e-02  9.0370312e-02 -3.4779113e-02
   1.3009547e-01  1.4527279e-01 -6.8328403e-02  6.1714694e-02
   1.0496302e-01  7.4521162e-02  7.9241514e-02  1.2149208e-01
   9.2848070e-02  1.6383871e-01  8.3695039e-02  1.1862928e-01
   8.4960550e-02  1.1424400e-01  4.4447754e-02 -1.4369994e-02
   1.7353597e-01  9.0383328e-02  7.3721111e-02  1.5649934e-01
   1.2394750e-01  5.7008471e-02  2.8602382e-02  1.5170257e-01
   2.2256730e-01  8.2103282e-02  3.8832251e-02  1.1789430e-01
   7.2601624e-03  1.2687095e-01  3.5189770e-02  2.0796658e-01
   4.8667630e-03  2.3524143e-02  7.3602879e-03  2.9564328e-03
  -1.0535795e-02 -1.8301873e-03 -1.0639500e-02 -9.1057261e-03
  -3.6039487e-03  1.5074311e-02  1.9646222e-03 -2.1895727e-02
   6.2935837e-03 -2.1919040e-02 -1.7654117e-02 -2.1218626e-02
  -6.8386488e-02 -3.7966847e-02 -3.1048129e-03 -6.9520874e-03
  -1.7304137e-02  1.0469861e-02  9.6158562e-03  4.2082183e-02
   3.4219876e-02 -1.7976945e-02  1.2334679e-02 -5.9613511e-03
  -4.1236766e-03 -1.0901124e-03  4.2627114e-03  1.5196125e-02]]
   [[ 0.00440907  0.10888897 -0.09616933 ... -0.03304675  0.10590862
   0.11304254]
 [-0.04049414  0.18468256 -0.17094377 ...  0.13760392 -0.19676338
  -0.11099713]
 [-0.02196838 -0.13418064  0.10111781 ...  0.05525769  0.05292984
  -0.00660474]
 ...
 [ 0.09352051  0.02894333  0.13384797 ...  0.01205626 -0.05097819
  -0.09016696]
 [-0.08773798 -0.1011564  -0.20588419 ...  0.08876771 -0.00020705
  -0.13049176]
 [ 0.09423009 -0.12560828 -0.15951984 ... -0.13902327 -0.19431512
   0.09943312]]
   [[-0.04495328 -0.06584636  0.02781093 ... -0.1586509   0.1276048
  -0.1137935 ]
 [ 0.02500164 -0.11050609 -0.04401826 ... -0.00679517 -0.27850327
  -0.17668006]
 [ 0.07231991 -0.05666076  0.06967113 ... -0.1911824   0.03664852
   0.13114648]
 ...
 [-0.05651525 -0.31177112  0.0980192  ...  0.07497717 -0.07345006
   0.0663117 ]
 [-0.04803313  0.02623563 -0.01468321 ... -0.02180142  0.00140534
  -0.08219719]
 [-0.12958223 -0.00195052 -0.13022879 ... -0.21793109  0.00790405
  -0.02220172]]
   [[-6.95314035e-02 -5.47517687e-02  8.75735879e-02  6.62586018e-02
  -4.12204936e-02 -6.32681325e-02  2.25645043e-02 -3.10157742e-02
  -5.24296938e-03 -5.11792377e-02 -3.13775502e-02  6.03959151e-02
  -2.29504984e-02 -1.05873473e-01  7.72524253e-03  6.82938322e-02
  -1.06765606e-01  7.03179017e-02 -9.56410728e-03 -2.99623199e-02
   4.06240486e-02 -6.74720900e-03  1.94848925e-02  7.68467560e-02
  -1.14373248e-02 -5.37250750e-02 -2.47544926e-02 -4.39222204e-03
  -7.16776997e-02 -2.31333449e-02 -2.03975998e-02 -6.26598746e-02
   1.24435179e-01  1.25774190e-01  1.14516176e-01  8.67636725e-02
   1.29334271e-01  1.50533482e-01  4.83456142e-02  3.64045165e-02
   6.33379519e-02  1.81998730e-01  1.29496872e-01  2.42907368e-02
  -3.90353263e-04  1.67674661e-01  7.93336034e-02  1.13840170e-01
   1.43721566e-01  9.17613432e-02  1.61869824e-01  1.12175897e-01
   1.40393123e-01  1.02932490e-01  9.50634703e-02  5.53398579e-02
   1.17537536e-01  1.16095752e-01  1.77141041e-01  1.17926903e-01
   9.47789028e-02  1.27038211e-01  6.51344433e-02  9.57336351e-02
  -1.50840646e-02 -9.32747778e-03 -1.13287829e-02  1.26184546e-03
  -5.01077948e-03  6.49370579e-03  6.13944978e-03  1.75886583e-02
   8.56223982e-03  1.32351480e-02  7.33586773e-03  2.63299122e-02
  -7.94736482e-03  1.53172594e-02 -2.47196723e-02 -3.02465782e-02
   8.43835901e-03 -5.23854792e-03 -2.19224915e-02  5.09755779e-03
   1.30099151e-02  8.33980180e-03  5.77431358e-03 -1.83468033e-02
  -2.61001885e-02 -2.16293801e-03  3.66357900e-02  4.48132050e-04
  -4.82865609e-03  3.63449343e-02  1.02573205e-02  7.58844195e-03]
 [-6.95314035e-02 -5.47517687e-02  8.75735879e-02  6.62586018e-02
  -4.12204936e-02 -6.32681325e-02  2.25645043e-02 -3.10157742e-02
  -5.24296938e-03 -5.11792377e-02 -3.13775502e-02  6.03959151e-02
  -2.29504984e-02 -1.05873473e-01  7.72524253e-03  6.82938322e-02
  -1.06765606e-01  7.03179017e-02 -9.56410728e-03 -2.99623199e-02
   4.06240486e-02 -6.74720900e-03  1.94848925e-02  7.68467560e-02
  -1.14373248e-02 -5.37250750e-02 -2.47544926e-02 -4.39222204e-03
  -7.16776997e-02 -2.31333449e-02 -2.03975998e-02 -6.26598746e-02
   1.24435179e-01  1.25774190e-01  1.14516176e-01  8.67636725e-02
   1.29334271e-01  1.50533482e-01  4.83456142e-02  3.64045165e-02
   6.33379519e-02  1.81998730e-01  1.29496872e-01  2.42907368e-02
  -3.90353263e-04  1.67674661e-01  7.93336034e-02  1.13840170e-01
   1.43721566e-01  9.17613432e-02  1.61869824e-01  1.12175897e-01
   1.40393123e-01  1.02932490e-01  9.50634703e-02  5.53398579e-02
   1.17537536e-01  1.16095752e-01  1.77141041e-01  1.17926903e-01
   9.47789028e-02  1.27038211e-01  6.51344433e-02  9.57336351e-02
  -1.42641682e-02  1.84351346e-03 -1.19567988e-02  2.46698246e-03
  -1.63169187e-02  6.65614964e-04  4.12170397e-04  2.67607383e-02
   1.81406460e-04  1.48952911e-02  1.25794802e-02  3.09836753e-02
  -1.78504251e-02  2.32329872e-02 -3.62559073e-02 -2.75095031e-02
   3.00829262e-02 -3.02481325e-03 -2.00695172e-02  9.34796780e-03
   1.51399281e-02  1.26724308e-02  5.22470940e-03 -1.74973719e-02
  -3.53103988e-02 -2.28428026e-03  3.12417392e-02  1.22774243e-02
  -1.22383032e-02  3.78843844e-02  5.78354672e-03  1.40918826e-03]]
Output-Layer
   [[-0.31721044]
 [-0.1957103 ]
 [-0.14846762]
 [-0.05705663]
 [ 0.25300348]
 [ 0.13566078]
 [ 0.15144905]
 [ 0.18582618]
 [ 0.29394606]
 [-0.21522617]
 [ 0.10908395]
 [-0.05756488]
 [-0.16305369]
 [ 0.04475483]
 [ 0.10303338]
 [ 0.06828187]
 [-0.05785383]
 [ 0.01367142]
 [-0.2851413 ]
 [-0.04511354]
 [ 0.06906123]
 [-0.03589668]
 [-0.2673274 ]
 [-0.11152817]
 [ 0.06082734]
 [ 0.01768485]
 [-0.18574184]
 [ 0.28629145]
 [-0.09949302]
 [-0.06112559]
 [ 0.06940149]
 [-0.1798325 ]
 [ 0.225608  ]
 [-0.19055592]
 [ 0.20848718]
 [-0.22900718]
 [ 0.25209734]
 [ 0.07387911]
 [ 0.16171443]
 [-0.15430118]
 [ 0.06112458]
 [-0.24384357]
 [-0.13787293]
 [-0.02061472]
 [-0.02848606]
 [-0.00122399]
 [ 0.32265964]
 [ 0.00908985]
 [-0.00251557]
 [ 0.23125929]
 [ 0.11075108]
 [-0.17022195]
 [-0.11843501]
 [-0.07102652]
 [-0.27981478]
 [ 0.21251921]
 [ 0.15072045]
 [ 0.08096407]
 [ 0.12319888]
 [-0.12308775]
 [-0.11064663]
 [-0.07575752]
 [ 0.11949602]
 [ 0.07903928]]
   [-0.00846349]

In [34]:
# Print the last value in the evaluation metrics contained within history file
print('-------------------- Evaluation on Training Data --------------------')
for item in history.history:
    print("Final", item, ":", history.history[item][-1])
print("")

-------------------- Evaluation on Training Data --------------------
Final loss : 0.009551760740578175
Final mean_absolute_error : 0.07848216593265533
Final mean_squared_error : 0.009551760740578175
Final val_loss : 0.03644381836056709
Final val_mean_absolute_error : 0.161009281873703
Final val_mean_squared_error : 0.03644381836056709

In [35]:
# Evaluate the model on the test data using "evaluate"
print('-------------------- Evaluation on Test Data --------------------')
results = model.evaluate(X_test, y_test)
print("")

-------------------- Evaluation on Test Data --------------------
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.0687 - mean_absolute_error: 0.2131 - mean_squared_error: 0.0687

In [36]:
# Plot average monthly temperatures (actual and predicted) for test (out of time) data
fig = go.Figure()

# Trace for actual temperatures
fig.add_trace(go.Scatter(x=np.array(dfloc_test.columns),
                         y=np.array(dfloc_test.values).flatten(),
                         mode='lines',
                         name='Average Monthly Temperatures - Actual (Test)',
                         opacity=0.8,
                         line=dict(color='black', width=1)
                        ))

# Trace for predicted temperatures
fig.add_trace(go.Scatter(x=np.array(dfloc_test.columns[-timestep:]),
                         y=scaler.inverse_transform(pred_test.reshape(-1,1)).flatten(),
                         mode='lines',
                         name='Average Monthly Temperatures - Predicted (Test)',
                         opacity=0.8,
                         line=dict(color='red', width=1)
                        ))

# Change chart background color
fig.update_layout(dict(plot_bgcolor = 'white'))

# Update axes lines
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='lightgrey',
                 zeroline=True, zerolinewidth=1, zerolinecolor='lightgrey',
                 showline=True, linewidth=1, linecolor='black',
                 title='Year-Month'
                )

fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='lightgrey',
                 zeroline=True, zerolinewidth=1, zerolinecolor='lightgrey',
                 showline=True, linewidth=1, linecolor='black',
                 title='Degrees Celsius'
                )

# Set figure title
fig.update_layout(title=dict(text="Average Monthly Temperatures", font=dict(color='black')),
                  legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
                 )

fig.show()