In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('train.txt',sep = ';',header = None,names = ['text','emotion'])

In [3]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

# Converting output variable in numeric terms

In [5]:
unique_emotions = df['emotion'].unique()
emotion_numbers = {}
i = 0

for emo in unique_emotions:
    emotion_numbers[emo] = i
    i+=1

df['emotion'] = df['emotion'].map(emotion_numbers)

In [6]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

# Lowercase

In [7]:
df['text'] = df['text'].apply(lambda x : x.lower())

# Removing Punctuation

In [8]:
import string

def remove_punc(txt):
    return txt.translate(str.maketrans('', '', string.punctuation))

df['text'] = df['text'].apply(remove_punc)

# Removing Numbers

In [9]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new+i
    return new

df['text'] = df['text'].apply(remove_numbers)

# Removing URLs/Links

In [10]:
# import re

In [11]:
# def remove_urls(text):
#     url_pattern = re.compile(r'https?://\S+|www\.\S+')
#     return url_pattern.sub(r'', text)

# df['text'] = df['text'].apply(remove_urls)

# Removing HTML Tags

In [12]:
# text = """<html><div>
# <h1>Natural Language Procesiong</h1>
# <p>Text Preprocessing for NLP</p>
# <a href="https://abc.com/@def">ABC Account</a>
# </div></html>
# """

# html_tags_pattern = r'<.*?>'

# # replace with empty where html_tags_pattern found
# text_without_html_tags = re.sub(html_tags_pattern, '', text)
# print(text_without_html_tags)

# Remove emogis and Special Characters

In [13]:
def remove_emogis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emogis)

# Remove stopwords e.g. is, the, was, in (Remove in ML context but keep in DL context)

In [14]:
import nltk

In [15]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [16]:
# nltk.download('punkt')
# nltk.download('stopwords')

In [17]:
stop_words = set(stopwords.words('english'))

In [18]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [19]:
def remove(txt):
  words = txt.split()
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)

  return ' '.join(cleaned)

df['text'] = df['text'].apply(remove)

In [20]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [21]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1