In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [2]:
# Tensorflow is engine and keras is driving wheel

In [3]:

df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [4]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [5]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [6]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [7]:
# Min Max Scaler
# Normalization data between 0 and 1
# Standardization average/mean whole data 0 and standard deviation 1 so values comes betweenand in very rare cases value goes over +2 and -2 +3 and -3

In [8]:
# In ML we used standardization but in DL will use normalization

X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [9]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.25, random_state=42, stratify=y
)

In [11]:
model = keras.Sequential([
    # shape means how much neurons for input
    layers.Input(shape= (X_train.shape[1],)),
    # activation function starts with layer 2, layer 1 is the input layer
    layers.Dense(8,activation= 'relu'),
    # output layer, activation function for binary classification 0 and 1
    layers.Dense(1,activation = 'sigmoid')
])

In [12]:
# applying a optimizer and loss function and metrics for evaluation accuracy used

model.compile(optimizer='adam',loss = 'binary_crossentropy',metrics= ['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [13]:
# Keras builds its mathematical execution graph during the very first .fit() call. When you switch back and forth between Pandas DataFrames and raw NumPy arrays mid-cell, or mix them within the same function call, Keras loses track of the tensor dimensions (its "rank"), resulting in the ValueError. Converting everything to .values ensures structural uniformity.

# 1. Full Batch Training (Convert to numpy arrays)
history_full = model.fit(
    X_train.values, y_train.values, 
    epochs=100, batch_size=len(X_train), verbose=1
)

# 2. Stochastic Training (Fixed: Added .values to X_test and y_test)
history = model.fit(
    X_train.values, y_train.values,
    validation_data=(X_test.values, y_test.values),
    epochs=100, batch_size=1, verbose=1
)

# 3. Mini-batch Training (Convert to numpy arrays)
# verbose means you wnat to see the changes what you are doing in your model 0 or 1
history_minibatch = model.fit(
    X_train.values, y_train.values, 
    epochs=100, batch_size=100, verbose=1
)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.4167 - loss: 0.7504
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.4167 - loss: 0.7490
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.4167 - loss: 0.7477
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.4167 - loss: 0.7464
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.4167 - loss: 0.7451
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.4167 - loss: 0.7439
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.4167 - loss: 0.7427
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.4167 - loss: 0.7416
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.3333 - loss: 0.7405
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.3333 - loss: 0.7395
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.3333 - loss: 0.7385
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.3333 - loss: 0.7375
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.3333 - loss: 0.7366
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.3333 - loss: 0.7357
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.3333 - loss: 0.7348
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.4167 - loss: 0.7339
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - accuracy: 0.3333 - loss: 0.7331
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - accuracy: 0.3333 - loss: 0.7323
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.3333 - loss: 0.7315
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.3333 - loss: 0.7307
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.3333 - loss: 0.7299
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.3333 - loss: 0.7292
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - accuracy: 0.2500 - loss: 0.7285
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.1667 - loss: 0.7278
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.1667 - loss: 0.7271
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.1667 - loss: 0.7264
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.2500 - loss: 0.7258
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.1667 - loss: 0.7251
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.1667 - loss: 0.7245
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.1667 - loss: 0.7238
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.1667 - loss: 0.7232
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.1667 - loss: 0.7226
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.2500 - loss: 0.7219
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.2500 - loss: 0.7213
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.2500 - loss: 0.7207
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.2500 - loss: 0.7201
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.2500 - loss: 0.7194
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.4167 - loss: 0.7188
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.4167 - loss: 0.7182
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.4167 - loss: 0.7175
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.4167 - loss: 0.7169
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.4167 - loss: 0.7164
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.4167 - loss: 0.7158
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.4167 - loss: 0.7152
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.4167 - loss: 0.7146
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.4167 - loss: 0.7141
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.4167 - loss: 0.7135
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.4167 - loss: 0.7129
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.4167 - loss: 0.7123
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.4167 - loss: 0.7118
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.4167 - loss: 0.7112
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.4167 - loss: 0.7106
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - accuracy: 0.4167 - loss: 0.7100
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.4167 - loss: 0.7095
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.4167 - loss: 0.7089
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.4167 - loss: 0.7083
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.4167 - loss: 0.7077
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.4167 - loss: 0.7072
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.4167 - loss: 0.7066
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.4167 - loss: 0.7060
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.5000 - loss: 0.7054
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.5000 - loss: 0.7049
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.5000 - loss: 0.7043
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.5000 - loss: 0.7037
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.5000 - loss: 0.7031
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.5000 - loss: 0.7026
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.5833 - loss: 0.7020
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.5833 - loss: 0.7014
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.5833 - loss: 0.7008
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.5833 - loss: 0.7003
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.5833 - loss: 0.6997
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.5833 - loss: 0.6991
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.5833 - loss: 0.6985
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.5833 - loss: 0.6980
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - accuracy: 0.5833 - loss: 0.6974
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.5833 - loss: 0.6968
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.5833 - loss: 0.6963
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.5833 - loss: 0.6957
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.5833 - loss: 0.6951
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.5833 - loss: 0.6945
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5833 - loss: 0.6940
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.5833 - loss: 0.6934
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.5833 - loss: 0.6928
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.5833 - loss: 0.6923
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.5833 - loss: 0.6917
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.6667 - loss: 0.6911
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.6667 - loss: 0.6905
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.6667 - loss: 0.6900
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.6667 - loss: 0.6894
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.6667 - loss: 0.6888
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.6667 - loss: 0.6883
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.6667 - loss: 0.6877
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - accuracy: 0.6667 - loss: 0.6871
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.6667 - loss: 0.6866
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.6667 - loss: 0.6860
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.6667 - loss: 0.6854
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.6667 - loss: 0.6849
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.6667 - loss: 0.6843
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.6667 - loss: 0.6837
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.6667 - loss: 0.6832
Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.6667 - loss: 0.6853 - val_accuracy: 0.5000 - val_loss: 0.6841
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6667 - loss: 0.6816 - val_accuracy: 1.0000 - val_loss: 0.6805
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6747 - val_accuracy: 1.0000 - val_loss: 0.6782
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6713 - val_accuracy: 0.7500 - val_loss: 0.6759
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6675 - val_accuracy: 0.7500 - val_loss: 0.6733
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6656 - val_accuracy: 0.7500 - val_loss: 0.6707
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6624 - val_accuracy: 0.7500 - val_loss: 0.6686
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6609 - val_accuracy: 0.7500 - val_loss: 0.6668
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6585 - val_accuracy: 0.7500 - val_loss: 0.6644
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6557 - val_accuracy: 0.7500 - val_loss: 0.6621
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6532 - val_accuracy: 0.7500 - val_loss: 0.6603
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6520 - val_accuracy: 0.7500 - val_loss: 0.6583
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6492 - val_accuracy: 0.7500 - val_loss: 0.6565
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6471 - val_accuracy: 0.7500 - val_loss: 0.6544
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6453 - val_accuracy: 0.7500 - val_loss: 0.6524
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.6430 - val_accuracy: 1.0000 - val_loss: 0.6504
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6411 - val_accuracy: 0.7500 - val_loss: 0.6486
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6397 - val_accuracy: 0.7500 - val_loss: 0.6467
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6377 - val_accuracy: 1.0000 - val_loss: 0.6449
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6361 - val_accuracy: 1.0000 - val_loss: 0.6428
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6348 - val_accuracy: 1.0000 - val_loss: 0.6412
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6667 - loss: 0.6320 - val_accuracy: 1.0000 - val_loss: 0.6394
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6302 - val_accuracy: 1.0000 - val_loss: 0.6374
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6667 - loss: 0.6284 - val_accuracy: 1.0000 - val_loss: 0.6354
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.6266 - val_accuracy: 1.0000 - val_loss: 0.6336
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6255 - val_accuracy: 1.0000 - val_loss: 0.6321
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6667 - loss: 0.6237 - val_accuracy: 1.0000 - val_loss: 0.6302
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6667 - loss: 0.6210 - val_accuracy: 1.0000 - val_loss: 0.6283
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6199 - val_accuracy: 1.0000 - val_loss: 0.6265
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.6173 - val_accuracy: 1.0000 - val_loss: 0.6249
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6156 - val_accuracy: 1.0000 - val_loss: 0.6233
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6137 - val_accuracy: 1.0000 - val_loss: 0.6215
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6121 - val_accuracy: 1.0000 - val_loss: 0.6196
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6103 - val_accuracy: 1.0000 - val_loss: 0.6182
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.6086 - val_accuracy: 1.0000 - val_loss: 0.6162
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6074 - val_accuracy: 1.0000 - val_loss: 0.6146
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6047 - val_accuracy: 1.0000 - val_loss: 0.6127
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6040 - val_accuracy: 1.0000 - val_loss: 0.6111
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6014 - val_accuracy: 1.0000 - val_loss: 0.6093
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.6002 - val_accuracy: 1.0000 - val_loss: 0.6075
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7500 - loss: 0.5981 - val_accuracy: 1.0000 - val_loss: 0.6058
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7500 - loss: 0.5963 - val_accuracy: 1.0000 - val_loss: 0.6039
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7500 - loss: 0.5944 - val_accuracy: 1.0000 - val_loss: 0.6022
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7500 - loss: 0.5930 - val_accuracy: 1.0000 - val_loss: 0.6007
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.5914 - val_accuracy: 1.0000 - val_loss: 0.5989
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7500 - loss: 0.5913 - val_accuracy: 1.0000 - val_loss: 0.5968
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7500 - loss: 0.5881 - val_accuracy: 1.0000 - val_loss: 0.5951
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7500 - loss: 0.5863 - val_accuracy: 1.0000 - val_loss: 0.5937
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.5843 - val_accuracy: 1.0000 - val_loss: 0.5916
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7500 - loss: 0.5833 - val_accuracy: 1.0000 - val_loss: 0.5898
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7500 - loss: 0.5814 - val_accuracy: 1.0000 - val_loss: 0.5881
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7500 - loss: 0.5793 - val_accuracy: 1.0000 - val_loss: 0.5863
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7500 - loss: 0.5780 - val_accuracy: 1.0000 - val_loss: 0.5844
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8333 - loss: 0.5757 - val_accuracy: 1.0000 - val_loss: 0.5829
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7500 - loss: 0.5739 - val_accuracy: 1.0000 - val_loss: 0.5813
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.5732 - val_accuracy: 1.0000 - val_loss: 0.5794
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.5704 - val_accuracy: 1.0000 - val_loss: 0.5778
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.5690 - val_accuracy: 1.0000 - val_loss: 0.5760
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.5683 - val_accuracy: 1.0000 - val_loss: 0.5743
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9167 - loss: 0.5655 - val_accuracy: 1.0000 - val_loss: 0.5723
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.5645 - val_accuracy: 1.0000 - val_loss: 0.5705
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.5631 - val_accuracy: 1.0000 - val_loss: 0.5688
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.5602 - val_accuracy: 1.0000 - val_loss: 0.5669
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9167 - loss: 0.5588 - val_accuracy: 1.0000 - val_loss: 0.5650
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9167 - loss: 0.5593 - val_accuracy: 1.0000 - val_loss: 0.5637
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9167 - loss: 0.5551 - val_accuracy: 1.0000 - val_loss: 0.5619
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9167 - loss: 0.5545 - val_accuracy: 1.0000 - val_loss: 0.5598
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.5518 - val_accuracy: 1.0000 - val_loss: 0.5580
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.5506 - val_accuracy: 1.0000 - val_loss: 0.5563
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9167 - loss: 0.5491 - val_accuracy: 1.0000 - val_loss: 0.5542
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.5473 - val_accuracy: 1.0000 - val_loss: 0.5524
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.5453 - val_accuracy: 1.0000 - val_loss: 0.5507
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9167 - loss: 0.5440 - val_accuracy: 1.0000 - val_loss: 0.5492
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9167 - loss: 0.5422 - val_accuracy: 1.0000 - val_loss: 0.5471
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9167 - loss: 0.5404 - val_accuracy: 1.0000 - val_loss: 0.5453
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.5395 - val_accuracy: 1.0000 - val_loss: 0.5435
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9167 - loss: 0.5373 - val_accuracy: 1.0000 - val_loss: 0.5417
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9167 - loss: 0.5358 - val_accuracy: 1.0000 - val_loss: 0.5396
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9167 - loss: 0.5349 - val_accuracy: 1.0000 - val_loss: 0.5380
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9167 - loss: 0.5346 - val_accuracy: 1.0000 - val_loss: 0.5359
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.5311 - val_accuracy: 1.0000 - val_loss: 0.5341
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.5293 - val_accuracy: 1.0000 - val_loss: 0.5321
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.5282 - val_accuracy: 1.0000 - val_loss: 0.5305
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9167 - loss: 0.5265 - val_accuracy: 1.0000 - val_loss: 0.5286
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.5246 - val_accuracy: 1.0000 - val_loss: 0.5266
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9167 - loss: 0.5227 - val_accuracy: 1.0000 - val_loss: 0.5248
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.5220 - val_accuracy: 1.0000 - val_loss: 0.5228
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9167 - loss: 0.5199 - val_accuracy: 1.0000 - val_loss: 0.5211
Epoch 89/100

In [14]:
from tensorflow.keras import optimizers

In [15]:
opt = optimizers.SGD(learning_rate = 0.01, momentum = 0.9)