In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [4]:
train_data = pd.read_csv('house_price_classification_cleaned.csv')

In [5]:
train_data.head()

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,YrSold,SaleType,SalePrice,PriceCategory,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,0,1,60,3,65.0,8450,1,1,3,3,...,2008,8,208500,2,0.0,0.0,0.0,0.0,1.0,0.0
1,1,2,20,3,80.0,9600,1,1,3,3,...,2007,8,181500,1,0.0,0.0,0.0,0.0,1.0,0.0
2,2,3,60,3,68.0,11250,1,1,0,3,...,2008,8,223500,2,0.0,0.0,0.0,0.0,1.0,0.0
3,3,4,70,3,60.0,9550,1,1,0,3,...,2006,8,140000,1,1.0,0.0,0.0,0.0,0.0,0.0
4,4,5,60,3,84.0,14260,1,1,0,3,...,2008,8,250000,2,0.0,0.0,0.0,0.0,1.0,0.0

In [6]:
y = train_data["PriceCategory"]
X = train_data.drop(["Id", "PriceCategory"], axis=1)

In [7]:
x_train_70, x_test_30, y_train_70, y_test_30 = train_test_split(X, y, test_size=0.3, random_state=42)
x_train_75, x_test_25, y_train_75, y_test_25 = train_test_split(X, y, test_size=0.25, random_state=42)
x_train_80, x_test_20, y_train_80, y_test_20 = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
X_train_70 = pd.concat([x_train_70, y_train_70], axis=1)
X_train_75 = pd.concat([x_train_75, y_train_75], axis=1)
X_train_80 = pd.concat([x_train_80, y_train_80], axis=1)

In [9]:
X_train_70.head()

,Unnamed: 0,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,YrSold,SaleType,SalePrice,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,PriceCategory
135,135,20,3,80.0,10400,1,1,3,3,0,...,2008,8,174000,0.0,0.0,0.0,0.0,1.0,0.0,1
1452,1452,180,4,35.0,3675,1,1,3,3,0,...,2006,8,145000,0.0,0.0,0.0,0.0,1.0,0.0,1
762,762,60,1,72.0,8640,1,1,3,3,0,...,2010,2,215200,0.0,0.0,0.0,0.0,1.0,0.0,2
932,932,20,3,84.0,11670,1,1,0,3,0,...,2007,8,320000,0.0,0.0,0.0,0.0,1.0,0.0,2
435,435,60,3,43.0,10667,1,1,1,3,0,...,2009,5,212000,0.0,0.0,0.0,0.0,1.0,0.0,2

In [10]:
X_train_70.to_csv("clean_train_70.csv", index=False)
X_train_75.to_csv("clean_train_75.csv", index=False)
X_train_80.to_csv("clean_train_80.csv", index=False)

In [11]:
X_train_70.head()

,Unnamed: 0,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,YrSold,SaleType,SalePrice,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,PriceCategory
135,135,20,3,80.0,10400,1,1,3,3,0,...,2008,8,174000,0.0,0.0,0.0,0.0,1.0,0.0,1
1452,1452,180,4,35.0,3675,1,1,3,3,0,...,2006,8,145000,0.0,0.0,0.0,0.0,1.0,0.0,1
762,762,60,1,72.0,8640,1,1,3,3,0,...,2010,2,215200,0.0,0.0,0.0,0.0,1.0,0.0,2
932,932,20,3,84.0,11670,1,1,0,3,0,...,2007,8,320000,0.0,0.0,0.0,0.0,1.0,0.0,2
435,435,60,3,43.0,10667,1,1,1,3,0,...,2009,5,212000,0.0,0.0,0.0,0.0,1.0,0.0,2

In [12]:
X_train_70["PriceCategory"].unique()

array([1, 2, 0])

In [13]:
X_train_70.shape

(1022, 87)

In [14]:
def datasplit(X, y):
  split_sizes = [0.3, 0.25, 0.2]
  dataframes = {}
  for test_size in split_sizes:

      X_train, X_test, y_train, y_test = train_test_split(
          X, y,
          test_size=test_size,
          random_state=42
      )

      train_percent = int((1 - test_size) * 100)

      df_name = f"df_train_{train_percent}"
      df = pd.concat([X_train, y_train], axis=1)

      dataframes[df_name] = df

      df.to_csv(f'/content/clean_train_{train_percent}.csv', index=False)

      print(f"{df_name} saved successfully!")

  return dataframes

In [15]:
datasplit(X, y)

df_train_70 saved successfully!
df_train_75 saved successfully!
df_train_80 saved successfully!

{'df_train_70':       Unnamed: 0  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
 135          135          20         3         80.0    10400       1      1
 1452        1452         180         4         35.0     3675       1      1
 762          762          60         1         72.0     8640       1      1
 932          932          20         3         84.0    11670       1      1
 435          435          60         3         43.0    10667       1      1
 ...          ...         ...       ...          ...      ...     ...    ...
 1095        1095          20         3         78.0     9317       1      1
 1130        1130          50         3         65.0     7804       1      1
 1294        1294          20         3         60.0     8172       1      1
 860          860          50         3         55.0     7642       1      1
 1126        1126         120         3         53.0     3684       1      1

       LotShape  LandContour  Utilities  ...  YrSold  SaleType  SalePrice  \
 135          3            3          0  ...    2008         8     174000
 1452         3            3          0  ...    2006         8     145000
 762          3            3          0  ...    2010         2     215200
 932          0            3          0  ...    2007         8     320000
 435          1            3          0  ...    2009         5     212000
 ...        ...          ...        ...  ...     ...       ...        ...
 1095         0            3          0  ...    2007         8     176432
 1130         3            3          0  ...    2009         8     135000
 1294         3            3          0  ...    2006         8     115000
 860          3            3          0  ...    2007         8     189950
 1126         3            3          0  ...    2009         8     174000

       SaleCondition_Abnorml  SaleCondition_AdjLand  SaleCondition_Alloca  \
 135                     0.0                    0.0                   0.0
 1452                    0.0                    0.0                   0.0
 762                     0.0                    0.0                   0.0
 932                     0.0                    0.0                   0.0
 435                     0.0                    0.0                   0.0
 ...                     ...                    ...                   ...
 1095                    0.0                    0.0                   0.0
 1130                    0.0                    0.0                   0.0
 1294                    0.0                    0.0                   0.0
 860                     0.0                    0.0                   0.0
 1126                    0.0                    0.0                   0.0

       SaleCondition_Family  SaleCondition_Normal  SaleCondition_Partial  \
 135                    0.0                   1.0                    0.0
 1452                   0.0                   1.0                    0.0
 762                    0.0                   1.0                    0.0
 932                    0.0                   1.0                    0.0
 435                    0.0                   1.0                    0.0
 ...                    ...                   ...                    ...
 1095                   0.0                   1.0                    0.0
 1130                   0.0                   1.0                    0.0
 1294                   0.0                   1.0                    0.0
 860                    0.0                   1.0                    0.0
 1126                   0.0                   1.0                    0.0

       PriceCategory
 135               1
 1452              1
 762               2
 932               2
 435               2
 ...             ...
 1095              1
 1130              0
 1294              0
 860               2
 1126              1

 [1022 rows x 87 columns],
 'df_train_75':       Unnamed: 0  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
 1023        1023         120         3         43.0     3182       1      1
 810          810          20         3         78.0    10140       1      1
 1384        1384          50         3         60.0     9060       1      1
 626          626          20         3         69.0    12342       1      1
 813          813          20         3         75.0     9750       1      1
 ...          ...         ...       ...          ...      ...     ...    ...
 1095        1095          20         3         78.0     9317       1      1
 1130        1130          50         3         65.0     7804       1      1
 1294        1294          20         3         60.0     8172       1      1
 860          860          50         3         55.0     7642       1      1
 1126        1126         120         3         53.0     3684       1      1

       LotShape  LandContour  Utilities  ...  YrSold  SaleType  SalePrice  \
 1023         3            3          0  ...    2008         8     191000
 810          3            3          0  ...    2006         8     181000
 1384         3            3          0  ...    2009         8     105000
 626          0            3          0  ...    2007         8     139900
 813          3            3          0  ...    2007         0     157900
 ...        ...          ...        ...  ...     ...       ...        ...
 1095         0            3          0  ...    2007         8     176432
 1130         3            3          0  ...    2009         8     135000
 1294         3            3          0  ...    2006         8     115000
 860          3            3          0  ...    2007         8     189950
 1126         3            3          0  ...    2009         8     174000

       SaleCondition_Abnorml  SaleCondition_AdjLand  SaleCondition_Alloca  \
 1023                    0.0                    0.0                   0.0
 810                     0.0                    0.0                   0.0
 1384                    0.0                    0.0                   0.0
 626                     0.0                    0.0                   0.0
 813                     0.0                    0.0                   0.0
 ...                     ...                    ...                   ...
 1095                    0.0                    0.0                   0.0
 1130                    0.0                    0.0                   0.0
 1294                    0.0                    0.0                   0.0
 860                     0.0                    0.0                   0.0
 1126                    0.0                    0.0                   0.0

       SaleCondition_Family  SaleCondition_Normal  SaleCondition_Partial  \
 1023                   0.0                   1.0                    0.0
 810                    0.0                   1.0                    0.0
 1384                   0.0                   1.0                    0.0
 626                    0.0                   1.0                    0.0
 813                    0.0                   1.0                    0.0
 ...                    ...                   ...                    ...
 1095                   0.0                   1.0                    0.0
 1130                   0.0                   1.0                    0.0
 1294                   0.0                   1.0                    0.0
 860                    0.0                   1.0                    0.0
 1126                   0.0                   1.0                    0.0

       PriceCategory
 1023              2
 810               1
 1384              0
 626               1
 813               1
 ...             ...
 1095              1
 1130              0
 1294              0
 860               2
 1126              1

 [1095 rows x 87 columns],
 'df_train_80':       Unnamed: 0  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
 254          254          20         3         70.0     8400       1      1
 1066        1066          60         3         59.0     7837       1      1
 638          638          30         3         67.0     8777       1      1
 799          799          50         3         60.0     7200       1      1
 380          380          50         3         50.0     5000       1      2
 ...          ...         ...       ...          ...      ...     ...    ...
 1095        1095          20         3         78.0     9317       1      1
 1130        1130          50         3         65.0     7804       1      1
 1294        1294          20         3         60.0     8172       1      1
 860          860          50         3         55.0     7642       1      1
 1126        1126         120         3         53.0     3684       1      1

       LotShape  LandContour  Utilities  ...  YrSold  SaleType  SalePrice  \
 254          3            3          0  ...    2010         8     145000
 1066         0            3          0  ...    2009         8     178000
 638          3            3          0  ...    2008         8      85000
 799          3            3          0  ...    2007         8     175000
 380          3            3          0  ...    2010         8     127000
 ...        ...          ...        ...  ...     ...       ...        ...
 1095         0            3          0  ...    2007         8     176432
 1130         3            3          0  ...    2009         8     135000
 1294         3            3          0  ...    2006         8     115000
 860          3            3          0  ...    2007         8     189950
 1126         3            3          0  ...    2009         8     174000

       SaleCondition_Abnorml  SaleCondition_AdjLand  SaleCondition_Alloca  \
 254                     0.0                    0.0                   0.0
 1066                    0.0                    0.0                   0.0
 638                     0.0                    0.0                   0.0
 799                     0.0                    0.0                   0.0
 380                     0.0                    0.0                   0.0
 ...                     ...                    ...                   ...
 1095                    0.0                    0.0                   0.0
 1130                    0.0                    0.0                   0.0
 1294                    0.0                    0.0                   0.0
 860                     0.0                    0.0                   0.0
 1126                    0.0                    0.0                   0.0

       SaleCondition_Family  SaleCondition_Normal  SaleCondition_Partial  \
 254                    0.0                   1.0                    0.0
 1066                   0.0                   1.0                    0.0
 638                    0.0                   1.0                    0.0
 799                    0.0                   1.0                    0.0
 380                    0.0                   1.0                    0.0
 ...                    ...                   ...                    ...
 1095                   0.0                   1.0                    0.0
 1130                   0.0                   1.0                    0.0
 1294                   0.0                   1.0                    0.0
 860                    0.0                   1.0                    0.0
 1126                   0.0                   1.0                    0.0

       PriceCategory
 254               1
 1066              1
 638               0
 799               1
 380               0
 ...             ...
 1095              1
 1130              0
 1294              0
 860               2
 1126              1

 [1168 rows x 87 columns]}